FROM node:20-alpine

WORKDIR /app

COPY frontend/frontend/package.json frontend/frontend/pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install

COPY frontend/frontend .

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]
