# Generated by Django 6.0 on 2026-01-01 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_date_joined_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(default='1111111111', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager')], default='OWNER', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
