# Generated by Django 6.0 on 2026-01-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_usercompany'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercompany',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
