# Generated by Django 6.0 on 2026-01-03 05:41

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_usercompany_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=auth_app.models.user_profile_image_path),
        ),
    ]
