# Generated by Django 5.1.3 on 2026-01-13 14:50

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '000X_enable_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='company_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tagline'], name='company_tagline_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_prefix', opclasses=['text_pattern_ops']),
        ),
    ]
