# Generated by Django 5.1.3 on 2026-02-04 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_company_company_name_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['display_order', '-rating_average', '-rating_count']},
        ),
        migrations.AddField(
            model_name='company',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, help_text='Lower number = higher priority in listings', null=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['display_order'], name='company_com_display_e83561_idx'),
        ),
    ]
