# Generated by Django 5.1.3 on 2026-02-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_company_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
