# Generated by Django 6.0 on 2026-01-01 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyonboardingrequest_companymembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyonboardingrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Company'), ('EXISTING', 'Existing Company')], default='NEW', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyonboardingrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyonboardingrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboarding_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyonboardingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
