# Generated by Django 5.1.3 on 2026-01-11 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_address_line_1_company_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companyonboardingrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
