# Generated by Django 6.0 on 2026-01-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. home.hero.title', max_length=255)),
                ('value', models.JSONField()),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('richtext', 'Rich Text'), ('list', 'List'), ('object', 'Object')], max_length=50)),
                ('page', models.CharField(help_text='e.g. home, about, footer', max_length=100)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'order'],
                'unique_together': {('key', 'page', 'locale')},
            },
        ),
    ]
