# Generated by Django 5.1.3 on 2026-01-12 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human readable name (e.g. Navbar Logo)', max_length=255)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('icon', 'Icon / SVG'), ('video', 'Video'), ('file', 'File')], default='image', max_length=20)),
                ('file', models.FileField(upload_to='assets/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
