# Generated by Django 5.1.3 on 2026-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_mediaasset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.CharField(blank=True, help_text="Country slug like 'canada', 'australia'. Leave empty for global content.", max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('key', 'page', 'locale', 'country')},
        ),
    ]
