# Generated by Django 5.1.3 on 2026-01-11 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
