# Generated by Django 5.1.3 on 2026-01-13 15:24

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcategory_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title'], name='blog_title_prefix', opclasses=['text_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='blog_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
