# Generated by Django 5.1.6 on 2026-03-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ['-created_at']},
        ),
    ]
