# Generated by Django 5.1.3 on 2026-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier e.g. REVIEW_APPROVED', max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='You can use placeholders like {{ username }}')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
