# Generated by Django 5.1.3 on 2026-01-07 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0006_emailtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='review_revi_is_appr_139439_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['moderation_status'], name='review_revi_moderat_86f800_idx'),
        ),
    ]
