# Generated by Django 5.1.3 on 2026-01-09 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0007_remove_review_review_revi_is_appr_139439_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'content_type', 'object_id'), name='unique_review_per_user_per_object'),
        ),
    ]