# Generated by Django 5.1.6 on 2026-02-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_emailtemplate_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
