# Generated by Django 5.1.6 on 2026-02-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_review_is_read_review_read_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['is_read', '-created_at']},
        ),
    ]
