import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProvider"
import Navbar from "@/components/header/navbar";
import { Footer } from "@/components/Footer"
import { ScrollProgressCircle } from "@/components/ScrollProgress"
import Breadcrumbs from "@/components/header/Breadcrumbs";
import { GlobalPrefetch } from "@/components/GlobalPrefetch";
import ToasterClient from "@/components/data-table/ToasterClient";
import AuthToasts from "@/components/AuthToast";
import { PageContentProvider } from "@/providers/PageContentProvider";
import Page from "./(marketing)/countries/[slug]/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PageContentProvider page="navbar">
            <Navbar/>
          </PageContentProvider>
          <Breadcrumbs/>
          <GlobalPrefetch />
          {children}
          <AuthToasts />
          <ToasterClient />
          <ScrollProgressCircle />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
